name: robert
favicon: null
layout_spectrum: 0.4973299764096737
typography_spectrum: 0.011732603190466762
title: Robert Barr
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.4258960715960711
  lightness: 0.7649737424217165
  saturation: 0.5059232388157398
  rhythmicContrast: 0.9554513145703822
purpose: []
